{
 "title": "Gatling",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "status", "query": "all,ok,ko" },
   {
    "name": "duration",
    "query": "min,mean,max,percentiles50,percentiles75,percentiles90,percentiles99"
   }
  ]
 },
 "panels": [
  { "title": "VUsers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling.users\" and\r\n      r.request != \"allUsers\"\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: last, offset: 1m)  "
    }
   ]
  },
  { "title": "Scenario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r._field == \"count\" and\r\n      r.status == \"${status}\" and\r\n      r.request == \"allRequests\"\r\n  )\r\n  |> group(columns: [\"simulation\", \"request\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.simulation} ${r.request}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r.status == \"${status}\" and\r\n      r.request != \"allRequests\" and\r\n      r._field == \"${duration}\"\r\n  )\r\n|> group(columns: [\"simulation\", \"request\"])  \r\n|> aggregateWindow(every: 1m, fn: mean, offset: 1m)  \r\n|> group(columns: [\"_time\",\"simulation\"], mode:\"by\")\r\n|> sum(column: \"_value\")\r\n|> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.simulation} allRequests\"\r\n}))\r\n|> group(columns: [\"name\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r._field == \"count\" and\r\n      r.status == \"${status}\" and\r\n      r.request == \"allRequests\"\r\n  )\r\n  |> group(columns: [\"simulation\", \"request\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.simulation} ${r.request}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, offset: 1m)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r._field == \"count\" and\r\n      r.status == \"${status}\" and\r\n      r.request != \"allRequests\"\r\n  )\r\n  |> group(columns: [\"simulation\", \"request\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.request}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r.status == \"${status}\" and\r\n      r.request != \"allRequests\" and\r\n      r._field == \"${duration}\"\r\n  )\r\n  |> group(columns: [\"request\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.request}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "Amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gatling\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"gatling\" and\r\n      r._field == \"count\" and\r\n      r.status == \"${status}\" and\r\n      r.request != \"allRequests\"\r\n  )\r\n  |> group(columns: [\"simulation\", \"request\"])\r\n  |> map(fn: (r) => ({\r\n     _value: r._value, \r\n     _time: r._time, \r\n     name: \"${r.request}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, offset: 1m)"
    }
   ]
  }
 ]
}