{
 "title": "System-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "group",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"telegraf\",\n    tag: \"group\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"telegraf\",\n    tag: \"host\",\n    predicate: (r) => r.group == \"${group}\",\n    start: -1d\n) "
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Total Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"cpu\" and\r\n      r._field == \"usage_idle\" and \r\n      r.cpu == \"cpu-total\" and\r\n      r.host == \"${host}\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n        _value: 100.0 - r._value, \r\n        _time: r._time, \r\n        name: \"${r.cpu}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "CPU Usage Per Core %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"cpu\" and\r\n      r._field == \"usage_idle\" and \r\n      r.cpu != \"cpu-total\" and\r\n      r.host == \"${host}\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n        _value: 100.0 - r._value, \r\n        _time: r._time, \r\n        name: \"${r.cpu}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "CPU Total Usage % Detalied",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"cpu\" and\r\n      r.cpu == \"cpu-total\" and\r\n      r._field != \"usage_idle\" and\r\n      r.host == \"${host}\"\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"mem\" and \r\n      r._field == \"used_percent\" and\r\n      r.host == \"${host}\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  {
   "title": "Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"mem\" and\r\n      r._field == \"used\" and\r\n      r.host == \"${host}\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and \r\n    r[\"_field\"] == \"total\" and\r\n    r.host == \"${host}\")\r\n  |> group(columns: [\"host\"])\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"_field\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"disk\" and\r\n      r._field == \"used_percent\" and\r\n      r.host == \"${host}\") \r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r.device} ${r.path} ${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)  "
    }
   ]
  },
  {
   "title": "Disk Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"disk\" and\r\n      r._field == \"used\" and\r\n      r.host == \"${host}\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r.device} ${r.path} ${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"disk\" and \r\n      r._field == \"total\" and\r\n      r.host == \"${host}\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r.device} ${r.path} ${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)  "
    }
   ]
  },
  {
   "title": "eShop db size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r[\"_measurement\"] == \"ls\" and\r\n     r[\"group\"] == \"${group}\" and\r\n     r[\"host\"] == \"${host}\")\r\n  |> group(columns: [\"lsfile\"])     \r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n\r\n\r\n  "
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Network Bytes In/Out Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"net\" and \r\n      r._field == \"bytes_recv\" and\r\n      r.host == \"${host}\")\r\n  |> group(columns: [\"interface\"])  \r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r.interface} ${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r._measurement == \"net\" and \r\n      r._field == \"bytes_sent\" and\r\n      r.host == \"${host}\")\r\n  |> group(columns: [\"interface\"])  \r\n  |> map(fn: (r) => ({\r\n        _value: r._value*-1, \r\n        _time: r._time, \r\n        name: \"${r.interface} ${r._field}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n  "
    }
   ]
  },
  {
   "title": "Network Bytes In/Out Amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" and \r\n   r.host == \"${host}\")\r\n  |> group(columns: [\"host\",\"interface\"])  \r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"interface\"]} ${r[\"_field\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> difference(nonNegative: true)\r\n  |> aggregateWindow(every: 1m, fn: sum, offset: 1m)\r\n\r\n  "
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" and \r\n   r.host == \"${host}\")\r\n  |> group(columns: [\"host\",\"interface\"])  \r\n  |> map(fn: (r) => ({\r\n        _value: r._value*-1, \r\n        _time: r._time, \r\n        name: \"${r[\"interface\"]} ${r[\"_field\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  |> difference(nonNegative: false)\r\n  |> aggregateWindow(every: 1m, fn: sum, offset: 1m)\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netstat\" and \r\n  r.host == \"${host}\")\r\n  |> group(columns: [\"_field\"])    \r\n  |> aggregateWindow(every: 1m, fn: mean, offset: 1m)\r\n\r\n\r\n  "
    }
   ]
  }
 ]
}