---
- name: Build load generator
  hosts: local
  connection: local
  tasks:
    - include_role:
        name: load_generator-role
        tasks_from: build

- name: Deploy load generator
  hosts: load_generator
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - include_role:
        name: load_generator-role
        tasks_from: deploy