apiVersion: 1

deleteDatasources:
  - name: InfluxDB

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    secureJsonData:
      token: Example-Token
    jsonData:
      version: Flux
      organization: main-org
