---
- name: Load instances configurations
  include_vars:
    name: instances
    file: instances.yml

- name: Create EC2 instances
  ec2:
    spot_price: "{{ item.value.spot_price }}"
    instance_initiated_shutdown_behavior: terminate
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ project_name }}-key"
    region: "{{ region }}"
    group_id: "{{ item.value.group_id }}"
    instance_type: "{{ item.value.instance_type }}"
    image: "{{ image }}"
    wait: yes
    instance_tags:
      name: "{{ item.key }}"
    count_tag:
      name: "{{ item.key }}"
    exact_count: 1
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
  register: ec2
  with_dict: "{{ instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.results | sum(attribute='tagged_instances',start=[]) }}"