- name: Add the newly created EC2 instances to host group
  lineinfile:
    dest: "{{ hostpath }}"
    insertafter: "{{ item.tags.name }}"
    line: "{{ item.public_ip }} {{ hoststring }}"
    state: present
  with_items: "{{ ec2.results | sum(attribute='tagged_instances',start=[]) }}"